home/urls.py
from . import views
from django.urls import include, path


urlpatterns = [
    path('', views.index, name='index'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('references', views.references, name='references'),
    path('contact', views.contact, name='contact'),
    path('category/<int:id>/<slug:slug>',
         views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>',
         views.product_detail, name='product_detail'),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.get_products, name='get_products'),



]

order/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('addtocart/<int:id>', views.addtocart, name='addtocart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
]

product/urls.py
from . import views
from django.contrib import admin
from django.urls import include,path


urlpatterns = [
    path('',views.index,name='index'),
    path('addcomment/<int:id>',views.addcomment,name='addcomment')
]

project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from order.views import shopcart

from user.views import loginUser,logoutUser,register


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('user.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),  # The CKEditor path
    path('shopcart/', shopcart, name='shopcart'),

    path('login/', loginUser, name='loginUser'),
    path('logout/', logoutUser, name='logoutUser'),
    path('register/', register, name='register'),

]
# + static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.forms import ModelForm

from product.models import Product, User

# Create your models here.


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def price(self):
        return (self.product.price)


class ShopCartform(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('Onshipping', 'Onshipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name',
                  'address', 'phone', 'city', 'country']


class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

product/models.py
from django.contrib.auth.models import User
from django.db import models
from autoslug import AutoSlugField
from django.forms import ModelForm
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from ckeditor_uploader.fields import RichTextUploadingField
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    STATUS = (
        ('true', 'evet'),
        ('false', 'hayır',),
    )
    title = models.CharField(max_length=140)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(
        upload_to='images/', default='images/resimyok.jpeg')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = AutoSlugField(populate_from='title')
    parent = TreeForeignKey('self', blank=True,  null=True,
                            related_name='children', on_delete=models.CASCADE)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class MPTTMeta:
        # level_attr = 'mptt_level's
        order_insertion_by = ['title']

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_slug(self):
        slug = slugify(self.title.replace("ı", "i"))
        unique = slug
        number = 1

        while Category.objects.filter(slug=unique).exists():
            unique = {}-{}.format(slug, number)
            number += 1
        return unique

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" width="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class Product(models.Model):
    STATUS = (
        ('true', 'evet'),
        ('false', 'hayır'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=140)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True,
                              upload_to='images/', default='images/resimyok.jpeg')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    amount = models.IntegerField()
    detail = RichTextUploadingField()
    slug = AutoSlugField(populate_from='title')
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_slug(self):
        slug = slugify(self.title.replace("ı", "i"))
        unique = slug
        number = 1

        while Product.objects.filter(slug=unique).exists():
            unique = {}-{}.format(slug, number)
            number += 1
        return unique

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" width="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class Images(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=130, blank=True)
    image = models.ImageField(
        upload_to='images/', default='images/resimyok.jpeg')

    class Meta:
        verbose_name = 'image'
        verbose_name_plural = 'images'

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height="50" width="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class Comment(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.TextField(max_length=200)
    rate = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS, default='True')
    ip = models.CharField(max_length=20, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['-create_at']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject', 'comment', 'rate']

order/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from order.models import Order, OrderForm, OrderProduct, ShopCart, ShopCartform
from product.models import Category, Product
from user.models import UserProfile
from django.utils.crypto import get_random_string
# Create your views here.


@login_required(login_url='/login')
def addtocart(request, id):
    url = request.META.get('HTTP_REFERER')
    checkproduct = ShopCart.objects.filter(
        product_id=id, user_id=request.user.id)
    if checkproduct:
        control = 1
    else:
        control = 0

    if request.method == 'POST':
        form = ShopCartform(request.POST)
        if form.is_valid():
            if control == 1:
                data = ShopCart.objects.get(product_id=id)
                data.user_id = request.user.id
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:
                data = ShopCart()
                data.user_id = request.user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
            request.session['cart_items'] = ShopCart.objects.filter(
                user_id=request.user.id).count()
            messages.success(
                request, 'The product has been successfully added to the cart.')
            return HttpResponseRedirect(url)

    else:
        if control == 1:

            data = ShopCart.objects.get(product_id=id)
            data.user_id = request.user.id
            data.quantity += 1
            data.save()
        else:
            data = ShopCart()
            data.user_id = request.user.id
            data.product_id = id
            data.quantity = 1
            data.save()
        request.session['cart_items'] = ShopCart.objects.filter(
            user_id=request.user.id).count()
        messages.success(
            request, 'The product has been successfully added to the cart.')
        return HttpResponseRedirect(url)
    messages.warning(
        request, 'An Error Occurred While Adding The Product To The Basket.')
    return HttpResponseRedirect(url)


@login_required(login_url='/login')
def shopcart(request):
    category = Category.objects.all()
    schopcart = ShopCart.objects.filter(user_id=request.user.id)
    request.session['cart_items'] = ShopCart.objects.filter(
        user_id=request.user.id).count()

    total = 0
    for rs in schopcart:
        total += rs.product.price * rs.quantity

    context = {
        'schopcart': schopcart,
        'category': category,
        'total': total,
    }
    return render(request, 'shopcart_products.html', context)


@login_required(login_url='/login')
def deletefromcart(request, id):
    ShopCart.objects.filter(id=id).delete()
    request.session['cart_items'] = ShopCart.objects.filter(
        user_id=request.user.id).count()
    messages.success(request, 'The product has been deleted from the cart.')
    return HttpResponseRedirect('/shopcart')


@login_required(login_url='/login')
def orderproduct(request):
    category = Category.objects.all()

    schopcart = ShopCart.objects.filter(user_id=request.user.id)
    total = 0
    for rs in schopcart:
        total += rs.product.price*rs.quantity

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = request.user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()
            data.code = ordercode
            data.save()

            schopcart = ShopCart.objects.filter(user_id=request.user.id)
            for rs in schopcart:
                detail = OrderProduct()
                detail.order_id = data.id
                detail.product_id = rs.product_id
                detail.user_id = request.user.id
                detail.quantity = rs.quantity
                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save()

                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()

            ShopCart.objects.filter(user_id=request.user.id).delete()
            request.session['cart_items'] = 0
            messages.success(
                request, 'Your Order has been completed. Thank You')
            return render(request, 'order_completed.html', {'ordercode': ordercode, 'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect('/order/orderproduct')

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=request.user.id)
    context = {
        'schopcart': schopcart,
        'category': category,
        'total': total,
        'form': form,
        'profile': profile,
    }

    return render(request, 'order_form.html', context)

product/views.py
from audioop import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from product.models import Comment, CommentForm
from django.contrib import messages


def index(request):
    return HttpResponse("Product Page")


@login_required(login_url='/login')
def addcomment(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user

            data = Comment()
            data.user_id = current_user.id
            data.product_id = id
            data.subject = form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()

            messages.success(
                request, 'Your Comment Has Been Submitted Successfully.')

            return HttpResponseRedirect(url)
    messages.error(request, 'Your comment could not be saved. Please check.')
    return HttpResponseRedirect(url)

templates/change_password.html
{% extends 'homebase.html' %}
{% load crispy_forms_tags %}
{% block title %}
  {{ profile.user }}
{% endblock %}

{% block keywords %}
  {{ setting.keywords }}
{% endblock %}

{% block description %}
  {{ setting.description }}
{% endblock %}

{% block head %}
  <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}" />
{% endblock %}

{% block sidebar %}
  {% include 'sidebar.html' %}
{% endblock %}

{% block content %}
  <!-- BREADCRUMB -->
  <div id="breadcrumb">
    <div class="container">
      <ul class="breadcrumb">
        <li>
          <a href="/">Anasayfa</a>
        </li>
        <li class="active">User Profile</li>
      </ul>
    </div>
  </div>
  <!-- /BREADCRUMB -->

  <!-- section -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-3">
          <div class="billing-details">

            {% include 'user_panel.html' %}


          </div>
        </div>

        <div class="col-md-9">
          <div class="section-title">
            <h3>Change Password</h3>
          </div>
            <div class="content-section">

                <form method="post">
                    {% csrf_token %}

                    <fieldset class="form-group">

                        {{form | crispy}}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-danger" type="submit">Save Changes</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /section -->
{% endblock %}

templates/footer.html
{% load static %}
<!-- FOOTER -->
	<footer id="footer" class="section section-grey">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<!-- footer logo -->
						<div class="footer-logo">
							<a class="logo" href="#">
		            <img src="{% static 'img/logo.png' %}" alt="">
		          </a>
						</div>
						<!-- /footer logo -->

						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna</p>

						<!-- footer social -->
						<ul class="footer-social">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
						</ul>
						<!-- /footer social -->
					</div>
				</div>
				<!-- /footer widget -->

				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">My Account</h3>
						<ul class="list-links">
							<li><a href="#">My Account</a></li>
							<li><a href="#">My Wishlist</a></li>
							<li><a href="#">Compare</a></li>
							<li><a href="#">Checkout</a></li>
							<li><a href="#">Login</a></li>
						</ul>
					</div>
				</div>
				<!-- /footer widget -->

				<div class="clearfix visible-sm visible-xs"></div>

				<!-- footer widget -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">Customer Service</h3>
						<ul class="list-links">
							<li><a href="#">About Us</a></li>
							<li><a href="#">Shiping & Return</a></li>
							<li><a href="#">Shiping Guide</a></li>
							<li><a href="#">FAQ</a></li>
						</ul>
					</div>
				</div>
				<!-- /footer widget -->

				<!-- footer subscribe -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="footer">
						<h3 class="footer-header">Stay Connected</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
						<form>
							<div class="form-group">
								<input class="input" placeholder="Enter Email Address">
							</div>
							<button class="primary-btn">Join Newslatter</button>
						</form>
					</div>
				</div>
				<!-- /footer subscribe -->
			</div>
			<!-- /row -->
			<hr>
			<!-- row -->
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<!-- footer copyright -->
					<div class="footer-copyright">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</div>
					<!-- /footer copyright -->
				</div>
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</footer>
	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

templates/index.html
{% extends 'homebase.html' %}

{% block title %}
  {{ setting.title }}
{% endblock %}

{% block keywords %}
  {{setting.keywords}}
{% endblock %}

{% block description %}
  {{setting.description}}
{% endblock %}

{% block head %}
  <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}" />
{% endblock %}

{% block sidebar %}
  {% include 'sidebar.html' %}
{% endblock %}

{% block slider %}
  {% include 'slider.html' %}
{% endblock %}

{% block content %}
  {% include 'content.html' %}
{% endblock %}

templates/product_detail.html
{% extends 'homebase.html' %}

{% block title %}
  {{ product.title }}
{% endblock %}

{% block keywords %}
  {{ setting.keywords }}
{% endblock %}

{% block description %}
  {{ setting.description }}
{% endblock %}

{% block head %}
  <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}" />
{% endblock %}

{% block sidebar %}
  {% include 'sidebar.html' %}
{% endblock %}

{% block content %}
  <!-- BREADCRUMB -->
  <div id="breadcrumb">
    <div class="container">
      <ul class="breadcrumb">
        <li>
          <a href="#">Home</a>
        </li>
        <li>
          <a href="#">Products</a>
        </li>
        <li>
          <a href="/category/{{ product.category_id }}/{{ product.category.slug }}">{{ product.category }}</a>
        </li>
        <li class="active">{{ product.title }}</li>
      </ul>
    </div>
  </div>
  <!-- /BREADCRUMB -->

  <!-- section -->
  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- Product Details -->
        <div class="product product-details clearfix">
          <div class="col-md-6">
            <div id="product-main-view">
              <div class="product-view">
                <img src="{{ product.image.url }}" alt="" />
              </div>
              {% for rs in images %}
                <div class="product-view" style="height: 350px;">
                  <img src="{{ rs.image.url }}" style="height: 300px; width: 300px;" alt="" />
                </div>
              {% endfor %}
            </div>

            <div id="product-view">
              <div class="product-view">
                <img src="{{ product.image.url }}" alt="" />
              </div>
              {% for rs in images %}
                <div class="product-view" style="height: 250px;">
                  <img src="{{ rs.image.url }}" alt="" />
                </div>
              {% endfor %}
            </div>
          </div>
          <div class="col-md-6">
            <div class="product-body">
              <div class="product-label">
                <span>New</span>
                <span class="sale">-20%</span>
              </div>
              <h2 class="product-name">{{ product.title }}</h2>
              <h3 class="product-price">{{ product.price }}</h3>
              <div>
                <div class="product-rating">
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                </div>
                <a href="#">3 Review(s) / Add Review</a>
              </div>
              <p>
                <strong>Availability:</strong> In Stock
              </p>
              <p>
                <strong>Brand:</strong> E-SHOP
              </p>
              <p>{{ product.description }}</p>

              <div class="product-btns">  
                <form action="/order/addtocart/{{product.id}}" method="post">
                  {% csrf_token %}
                  <div class="qty-input">
                    <span class="text-uppercase">ADET:</span>
                  <input name="quantity" class="input" type="number" min="0" max="{{ product.amount }}" value="1" />
                </div>
                <button type="submit" class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add To Cart</button>
                </form>
              </div>
    
                <div class="pull-right">
                  <button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
                  <button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
                  <button class="main-btn icon-btn"><i class="fa fa-share-alt"></i></button>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-12">
            <div class="product-tab">
              <ul class="tab-nav">
                <li class="active">
                  <a data-toggle="tab" href="#tab1">Details</a>
                </li>
                <li>
                  <a data-toggle="tab" href="#tab2">Reviews</a>
                </li>
              </ul>
              <div class="tab-content">
                <div id="tab1" class="tab-pane fade in active">
                  <p>{{ product.detail|safe }}</p>
                </div>
                <div id="tab2" class="tab-pane fade in">
                  <div class="row">
                    <div class="col-md-6">
                      <div class="product-reviews">
                        
                        {% for rs in comments %}
                        <div class="single-review">
                          <div class="review-heading">
                            <div>
                              <a href="#"><i class="fa fa-user-o"></i> {{rs.user.first_name}}</a>
                            </div>
                            <div>
                              <a href="#"><i class="fa fa-clock-o"></i> {{rs.create_at}} </a>
                            </div>
                            <div class="review-rating pull-right">
                              <i class="fa fa-star {% if rs.rate < 1 %}-o empty {% endif %}"></i>
                              <i class="fa fa-star {% if rs.rate < 2 %}-o empty {% endif %}"></i>
                              <i class="fa fa-star {% if rs.rate < 3 %}-o empty {% endif %}"></i>
                              <i class="fa fa-star {% if rs.rate < 4 %}-o empty {% endif %}"></i>
                              <i class="fa fa-star {% if rs.rate < 5 %}-o empty {% endif %}"></i>
                            </div>
                          </div>
                          <div class="review-body"> 
                            <b> {{rs.subject}} </b>
                            <p> {{rs.comment}} </p>
                          </div>
                        </div>
                        {% endfor %}
                        <ul class="reviews-pages">
                          <li class="active">1</li>
                          <li>
                            <a href="#">2</a>
                          </li>
                          <li>
                            <a href="#">3</a>
                          </li>
                          <li>
                            <a href="#"><i class="fa fa-caret-right"></i></a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="col-md-6">
                        {% if user.id is None %}
                        <a href="/login" class="btn btn-danger">Yorum Yapabilmek İçin GİRİŞ Yapınız.</a>
                        {% else %}

                      <h4 class="text-uppercase">Write Your Review</h4>
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
                            {% endfor %}
                        {% endif %}
                      <form class="review-form" action="/product/addcomment/{{ product.id }}"  method="post">
                        {% csrf_token %}
                        <div class="form-group">
                          <input class="input" type="text" name="subject" id="id_subject" placeholder="Subject" />
                        </div>
                        <div class="form-group">
                          <textarea class="input" name="comment" id="id_comment" placeholder="Your review"></textarea>
                        </div>
                        <div class="form-group">
                          <div class="input-rating">
                            <strong class="text-uppercase">Your Rating:</strong>
                            <div class="stars">
                              <input type="radio" id="star5" name="rate" value="5" /><label for="star5"></label>
                              <input type="radio" id="star4" name="rate" value="4" /><label for="star4"></label>
                              <input type="radio" id="star3" name="rate" value="3" /><label for="star3"></label>
                              <input type="radio" id="star2" name="rate" value="2" /><label for="star2"></label>
                              <input type="radio" id="star1" name="rate" value="1" /><label for="star1"></label>
                            </div>
                          </div>
                        </div>
                        <button class="primary-btn">Yorum Yap</button>
                      </form>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /Product Details -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /section -->
{% endblock %}

templates/references.html
{% extends 'homebase.html' %}

{% block title %}
  {{ setting.company }}-Referanslar
{% endblock %}

{% block keywords %}
  {{setting.keywords}}
{% endblock %}

{% block description %}
  {{setting.description}}
{% endblock %}

{% block head %}
  <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}" />
{% endblock %}

{% block sidebar %}
  {% include 'sidebar.html' %}
{% endblock %}


{% block content %}
    <!-- BREADCRUMB -->
	<div id="breadcrumb">
		<div class="container">
			<ul class="breadcrumb">
				<li><a href="/">HomePage</a></li>
				<li class="active">References</li>
			</ul>
		</div>
	</div>
	<!-- /BREADCRUMB -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
                {{setting.references | safe}}
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->



{% endblock %}